### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by corysimmons** [markalfred/jeet-snippets#3]
I keep trying to `tab` after something like `cyc` but it doesn't do anything. I thought it might be Emmet messing with it, but I disabled it.

Any ideas?

**Comment by markalfred** [comment]
Is it in the scope of a function's arguments (and in a `.styl` file)? I scoped the snippets pretty narrowly so that they don't show up everywhere. So, for instance, typing `cyc` at the top of a `.styl` file won't do anything, but typing `foo(c` will bring up the `cycle` snippet along with others. I need to review the full API thoroughly, because I'm sure some things are missing — but in general, [`function`](https://github.com/markalfred/jeet-snippets/tree/master/functions) snippets are available anywhere in a `.styl` file, and [`argument`](https://github.com/markalfred/jeet-snippets/tree/master/arguments) snippets are only available [inside the arguments of a function](https://github.com/markalfred/jeet-snippets/blob/master/arguments/align.sublime-snippet#L6).

Debatable whether this adds any value or whether it just makes the snippets less intuitive / more prone to bugs.

**Comment by corysimmons** [comment]
Got it working with Emmet disabled but with Emmet enabled it overpowers Jeet Snippets.

``` stylus
.foo
  col(cyc[tab]
```

renders

``` stylus
.foo
  col(color: #000
```

Thoughts?

**Comment by markalfred** [comment]
Pressing tab here...

![image](https://cloud.githubusercontent.com/assets/3876443/3999120/c351b6dc-294d-11e4-9b29-57738b0302c5.png)

...results in

![image](https://cloud.githubusercontent.com/assets/3876443/3999128/d6fc008e-294d-11e4-8185-fc3098c77a94.png)

Pressing tab here...

![image](https://cloud.githubusercontent.com/assets/3876443/3999108/b7c9b7a6-294d-11e4-8e48-64fb30aeead5.png)

 ...results in

![image](https://cloud.githubusercontent.com/assets/3876443/3999144/f14b95c6-294d-11e4-8291-1f5e7acf9151.png)

But I think that's by design...

**Comment by corysimmons** [comment]
https://github.com/markalfred/jeet-snippets/issues/6
